# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import insight_pb2 as insight__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in insight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionServiceStub(object):
    """VisionService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstimateVolume = channel.unary_unary(
                '/insight.VisionService/EstimateVolume',
                request_serializer=insight__pb2.VolumeRequest.SerializeToString,
                response_deserializer=insight__pb2.VolumeResponse.FromString,
                _registered_method=True)


class VisionServiceServicer(object):
    """VisionService
    """

    def EstimateVolume(self, request, context):
        """Ham uoc luong the tich
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstimateVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateVolume,
                    request_deserializer=insight__pb2.VolumeRequest.FromString,
                    response_serializer=insight__pb2.VolumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'insight.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('insight.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService(object):
    """VisionService
    """

    @staticmethod
    def EstimateVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/insight.VisionService/EstimateVolume',
            insight__pb2.VolumeRequest.SerializeToString,
            insight__pb2.VolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GLServiceStub(object):
    """GL calculation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateGL = channel.unary_unary(
                '/insight.GLService/CalculateGL',
                request_serializer=insight__pb2.GLRequest.SerializeToString,
                response_deserializer=insight__pb2.GLResponse.FromString,
                _registered_method=True)


class GLServiceServicer(object):
    """GL calculation
    """

    def CalculateGL(self, request, context):
        """Ham tinh GL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateGL': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateGL,
                    request_deserializer=insight__pb2.GLRequest.FromString,
                    response_serializer=insight__pb2.GLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'insight.GLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('insight.GLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GLService(object):
    """GL calculation
    """

    @staticmethod
    def CalculateGL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/insight.GLService/CalculateGL',
            insight__pb2.GLRequest.SerializeToString,
            insight__pb2.GLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RAGServiceStub(object):
    """Rag Advisor
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAdvice = channel.unary_unary(
                '/insight.RAGService/GetAdvice',
                request_serializer=insight__pb2.AdviceRequest.SerializeToString,
                response_deserializer=insight__pb2.AdviceResponse.FromString,
                _registered_method=True)


class RAGServiceServicer(object):
    """Rag Advisor
    """

    def GetAdvice(self, request, context):
        """Ham lay loi khuyen tiem Insulin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAdvice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdvice,
                    request_deserializer=insight__pb2.AdviceRequest.FromString,
                    response_serializer=insight__pb2.AdviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'insight.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('insight.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """Rag Advisor
    """

    @staticmethod
    def GetAdvice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/insight.RAGService/GetAdvice',
            insight__pb2.AdviceRequest.SerializeToString,
            insight__pb2.AdviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
